### PR TITLE
fix(sa): add userEntityId when creating service accounts

### PR DESCRIPTION
**Pull request by Phil91**
## Description

- add userEntityId when creating a company service account
- add process to update the userEntityId for company service accounts that don't have the userEntityId set correctly

## Why

Currently when creating a company service account the userEntityId is not set correctly

## Issue

N/A - JIra Issue: CPLP-3342

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by ntruchsess — DISMISSED** [review]
I did rebase on dev recreating the migration.
Furthermore I did refactor the process-step to request save after each synchronized identity. While this certainly will result in more requests to be executed on the database it ensures no synchronized identity is lost in case the transaction prematurely ends.
Unit-test is adjusted accordingly.
Please double-check

**Review by ntruchsess — APPROVED** [review]
I did rebase on dev recreating the migration.
Furthermore I did refactor the process-step to request save after each synchronized identity. While this certainly will result in more requests to be executed on the database it ensures no synchronized identity is lost in case the transaction prematurely ends.
Unit-test is adjusted accordingly.
Please double-check

**Comment by Phil91** [comment]
> I did rebase on dev recreating the migration. Furthermore I did refactor the process-step to request save after each synchronized identity. While this certainly will result in more requests to be executed on the database it ensures no synchronized identity is lost in case the transaction prematurely ends. Unit-test is adjusted accordingly. Please double-check

looks good to me. i think thats a good decision, if the process fails we don't need to proceed all entities again.

**Review by ntruchsess — CHANGES_REQUESTED** [review]
just noticed that the refactored implementation might have an issue in case the retrieval of the userEntityId fails and the identity is not updated. In this case the process might retry endlessly to update the very same identity, so I'm going to revert most of the last commit.

**Comment by Phil91** [comment]
Somehow the dependency build fails. I've created IP Issues for the failing packages:

- [ ] [nuget/nuget/-/Newtonsoft.Json/12.0.2](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/11114)
- [ ] [nuget/nuget/-/Serilog.Formatting.Compact/1.1.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/11115)
- [ ] [nuget/nuget/-/Serilog.Sinks.File/5.0.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/11116)

**Comment by Phil91** [comment]
We won't update the dependency file before merging the PR. The checks were fine in previous checks of the dashtool. therefor we will wait for the approval of ip issue [nuget/nuget/-/Newtonsoft.Json/12.0.2](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/11114) before updating the dependency file.

**Review by ntruchsess — APPROVED** [review]

**Pull request merged**
