### PR TITLE
feat(invitation): allow access to invitation endpoint to technical user

### PR DESCRIPTION
**Pull request by typecastcloud**
## Description

Allow access to invitation endpoint to technical user.

## Why

Technical user/clients were not able to use endpoint.

## Issue

Refs: #932

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have checked that new and existing tests pass locally with my changes

### CODE REVIEW

**Comment by Phil91** [comment]
@typecastcloud please update the dependencies. can be found in the artefacts here: https://github.com/eclipse-tractusx/portal-backend/actions/runs/10402110437?pr=933

**Comment by typecastcloud** [comment]
> @typecastcloud please update the dependencies. can be found in the artefacts here: https://github.com/eclipse-tractusx/portal-backend/actions/runs/10402110437?pr=933

I rebased to release/v2.2.0-RC4 branch. Tests are failing on that branch. Not sure if that also resolved dependencies.

> @typecastcloud please update the dependencies. can be found in the artefacts here: https://github.com/eclipse-tractusx/portal-backend/actions/runs/10402110437?pr=933

**Comment by evegufy** [comment]
Hi @typecastcloud I suggest to do an interactive rebase dropping all commits that aren't yours

**Comment by typecastcloud** [comment]
> Hi @typecastcloud I suggest to do an interactive rebase dropping all commits that aren't yours

Done. Rebased on RC5. Not sure why this PR wants updated dependencies.

**Review by evegufy — APPROVED** [review]
@MaximilianHauer could you please review as well?

**Review by Phil91 — APPROVED** [review]

**Comment by evegufy** [comment]
> @MaximilianHauer could you please review as well?

Just sawhttps://github.com/eclipse-tractusx/portal-backend/issues/932#issuecomment-2320514899

**Comment by typecastcloud** [comment]
> > @MaximilianHauer could you please review as well?
> 
> Just saw [#932 (comment)](https://github.com/eclipse-tractusx/portal-backend/issues/932#issuecomment-2320514899)

I'll create a separate PR for this since it requires more complex additions to the code base.

**Pull request merged**
