### PR TITLE
feat(searchpost): update pattern search same company name for post endpoint

### PR DESCRIPTION
**Pull request by AnuragNagpure**
## Description

adjust existing endpoints where company name is getting inserted with the same pattern as used for search of company names.
Changes occur in below endpoints:
POST: api/administration/invitation
GET: api/administration/registration/applicationsWithStatus?page=0&amp;size=15</remarks>
GET: api/administration/registration/applications?page=0&amp;size=4
POST: api/administration/registration/network/partnerRegistration
POST: api/registration/application/{applicationId}/companyDetailsWithAddress
PUT: /api/apps/appreleaseprocess/15507472-dfdc-4885-b165-8d4a8970a3e2
POST: /api/apps/appreleaseprocess/createapp

## Why

Pattern harmonization across all endpoints where the company name is entered.

## Issue

N/A Ref: CPLP-3564
N/A Ref: CPLP-3562

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by jjeroch — CHANGES_REQUESTED** [review]
@AnuragNagpure change of the pr needed.
Please mention inside the PR description all updated endpoints
For the "Why" an update is needed as well. Why are we doing the change? Reason: Pattern harmonization across all endpoints where the company name is entered.

Last but not least; thats a breaking change and related to a FE PR - both should be mentioned as a comment and breaking change to be highlighted via a label

**Review by Phil91 — CHANGES_REQUESTED** [review]
Besides the endpoints you adjusted I found two additional endpoints.

Please add the validation there as well:

POST: api/administration/registration/network/partnerRegistration
Post: /api/registration/application/{applicationId}/companyDetailsWithAddress

**Comment by AnuragNagpure** [comment]
> Besides the endpoints you adjusted I found two additional endpoints.
> 
> Please add the validation there as well:
> 
> POST: api/administration/registration/network/partnerRegistration Post: /api/registration/application/{applicationId}/companyDetailsWithAddress

Changes done

**Review by Phil91 — APPROVED** [review]

**Comment by Phil91** [comment]
Frontend PR was already merged:

https://github.com/eclipse-tractusx/portal-frontend/pull/403

**Review by Phil91 — CHANGES_REQUESTED** [review]
after a short discussion with julia there were some app / service endpoints which came up:

POST: /api/services/servicerelease/addservice
PUT: /api/apps/appreleaseprocess/15507472-dfdc-4885-b165-8d4a8970a3e2
POST: /api/apps/appreleaseprocess/createapp
POST: /api/services/servicerelease/addservice

please add the validation for thoses endpoints as well. the field which should be validated here is the provider

**Comment by AnuragNagpure** [comment]
> after a short discussion with julia there were some app / service endpoints which came up:
> 
> POST: /api/services/servicerelease/addservice PUT: /api/apps/appreleaseprocess/15507472-dfdc-4885-b165-8d4a8970a3e2 POST: /api/apps/appreleaseprocess/createapp POST: /api/services/servicerelease/addservice
> 
> please add the validation for thoses endpoints as well. the field which should be validated here is the provider

changes done

**Review by Phil91 — APPROVED** [review]

**Comment by Phil91** [comment]
@AnuragNagpure please add the adjusted endpoints to the ticket in jira as well.

**Pull request merged**
