### PR TITLE
fix(decline): moved email validation in decline application process api

### LINKED ISSUE #820: Company application cancellation | Receives 409 upon cancelling the application process.
### Current Behavior
Getting 409 error on passing blank comment in cancelling application process and if we try again then we get keycloak error (500)

### Expected Behavior
If no comment has been passed then Cancel api should give error in early stage but it should pass after providing the comment 

### Steps To Reproduce

1. Login to the application as a CX admin
2. Go to application requests 
3. Click on “Cancel“ button
4. Do not add any cancellation message
5. Click “confirm“ Button , you will get the 409 error
6. Now add comment and then click confirm again
7. it will throw error for "clientId *** not found on shared idp"

### Error Response
```json
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.8 ",
    "title": "The resorce is in conflict with the current request.",
    "status": 409,
    "errors": {
        "Org.Eclipse.TractusX.Portal.Backend.Administration.Service": [
            "No comment set."
        ]
    },
    "errorId": "08a46cb4-39f8-4b56-bd61-79834af0556a",
    "details": []
}
```

when Admin tries to cancel the same Company process along with Cancellation message then system returns below error message.
```json
{
  "type": "https://datatracker.ietf.org/doc/html/rfc7231#section-6.6.1",
  "title": "The server encountered an unexpected condition.",
  "status": 500,
  "errors": {
    "Org.Eclipse.TractusX.Portal.Backend.Provisioning.Library": [
      "clientId saidp8 not found on shared idp"
    ]
  },
  "errorId": "43962feb-13a0-4c1c-baae-7811ea3e87ab",
  "details": []
}
```

### Expected Fix
Move comment validation in before other code get executed

### PR DESCRIPTION
**Pull request by dhiren-singh-007**
## Description

Moved the validation of blank or null comment from child method to parent method.
fixes #820  closes #820 

## Why

There is a required validation on the comment field at a later stage in this API. Before this, the code makes a call to Keycloak to delete the client for this company.
If we call this API with a blank comment, it throws an exception after deleting the data from Keycloak.
and after that its impossible to cancel the application process

## Issue

[#820](https://github.com/eclipse-tractusx/portal-backend/issues/820)

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes

### CODE REVIEW

**Review by Phil91 — APPROVED** [review]
lgtm

**Review by Phil91 — COMMENTED** [review]
@dhiren-singh-007 could you please change the target branch to release/v2.1.0-RC1 and rebase your branch to the branch

**Comment by dhiren-singh-007** [comment]
@Phil91 : thanks , i have changed the target branch and did the rebase from release/v2.1.0-RC1 . Please tell me if I did rebase correctly because it is showing other commits also ?

**Comment by dhiren-singh-007** [comment]
closing the PR as rebase went wrong and created a new PR [#822](https://github.com/eclipse-tractusx/portal-backend/pull/822)

**Pull request closed without merging**
