### PR TITLE
test(e2e): merge test automation

### PR DESCRIPTION
**Pull request by evegufy**
## Description

This PR build on https://github.com/eclipse-tractusx/portal-backend/pull/110 and does apply the following changes:
- fix obsolete model reference
- set AssemblyName and RootNamespace
- fix packagereference and namespace in a couple of files
- add file header
- update reportportal package
- update dependencies

## Why

enable test automation via manually triggered GH workflow

## Issue

n/a

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own changes
- [x] I have successfully tested my changes locally

### CODE REVIEW

**Comment by evegufy** [comment]
@Phil91 as discussed, I may remove the filter here https://github.com/eclipse-tractusx/portal-backend/pull/230/files#diff-264dbf2dfb44fa78367056cb5d3f80b7ab2ab369b075c378cd719cbe0f1ce916R52 if not working.
The e2e tests are hitting error in this GH organization before being able not to pass (I assume due to missing settings), which apparently results in successful run, but I just thought about the fork...: there we should probably disable then the workflow as it'd currently runs with every sync (and the setting are available there): https://github.com/catenax-ng/tx-portal-backend/actions/workflows/unit.tests-formatting.yml

**Comment by evegufy** [comment]
@Phil91 as discussed could you please rebase again and have a look at this issue: https://github.com/catenax-ng/tx-portal-backend/actions/runs/6187678959/job/16798040693#step:14:16

**Comment by Phil91** [comment]
Pending Eclipse PRs

-[ ] [nuget/nuget/-/ReportPortal.XUnit/2.5.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10588)
-[ ] [nuget/nuget/-/ReportPortal.Shared/3.6.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10587)

**Comment by evegufy** [comment]
@Phil91 as discussed, I squashed the last 10 commits into a new one, PR is ready for review now.

**Review by Phil91 — APPROVED** [review]

**Review by Phil91 — APPROVED** [review]

**Pull request merged**
