### PR TITLE
feat(seeding): move company and address to overwrite dir

### PR DESCRIPTION
**Pull request by Phil91**
## Description

move company and address seeding files to overwrite dir

## Why

to provide the option to seed the bpn without changing the code it's moved into a directory where it can be overwritten

## Issue

Refs: https://github.com/eclipse-tractusx/portal/issues/449

## Corresponding Portal PR

https://github.com/eclipse-tractusx/portal/pull/450

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by evegufy — DISMISSED** [review]
lgtm 👍 
just, could we do the update of the api specs version in a separate pr?

**Comment by Phil91** [comment]
> lgtm 👍 just, could we do the update of the api specs version in a separate pr?

removed from here. will create a separate pr for that

**Review by ntruchsess — APPROVED** [review]

**Review by evegufy — CHANGES_REQUESTED** [review]
Looks good in general, just the api spec files should not be part of the change: could you please review https://github.com/eclipse-tractusx/portal-backend/pull/1077? And once it is merged, rebase to main?

**Comment by Phil91** [comment]
> Looks good in general, just the api spec files should not be part of the change: could you please review #1077? And once it is merged, rebase to main?

done

**Review by evegufy — APPROVED** [review]
Tested successfully

**Pull request merged**
