### PR TITLE
feat(certificate): enhance company certificate db attributes and API details

### PR DESCRIPTION
**Pull request by AnuragNagpure**
## Description

Need to add additional parameters in company_certificate(externalcertificatenumber, sites, validfrom, validtill, issuer, validator) table along with additional table companies_certificate_assigned_sites to link mutiple sites(BPNS) with comapanycertificate id.

After changes in db need to change Post and get endpoints as mentioned below:
 POST: api/administration/companydata/companyCertificate
 GET /api/administration/companydata/companyCertificates
 GET: api/administration/companydata/businessPartnerNumber}/companyCertificates

Also validation added parameters also need to implement.

## Why

For tracking multiple BPNS against companies this implementation is required.

## Issue

#574 

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by evegufy — CHANGES_REQUESTED** [review]
Hi @AnuragNagpure could you please solve the codeql finding and clarify the milestone of the https://github.com/eclipse-tractusx/portal-backend/issues/574 with @jjeroch , currently still set to our already released 2.0.0 version ...

**Review by ntruchsess — DISMISSED** [review]

**Review by ntruchsess — APPROVED** [review]

**Comment by ntruchsess** [comment]
> Hi @AnuragNagpure could you please solve the codeql finding and clarify the milestone of the #574 with @jjeroch , currently still set to our already released 2.0.0 version ...

I dismissed the codeql-finding as false positive (see comment)

**Comment by AnuragNagpure** [comment]
> > Hi @AnuragNagpure could you please solve the codeql finding and clarify the milestone of the #574 with @jjeroch , currently still set to our already released 2.0.0 version ...
> 
> I dismissed the codeql-finding as false positive (see comment)

Hi @ntruchsess its milestone is set as 24.12

**Review by ntruchsess — CHANGES_REQUESTED** [review]
@AnuragNagpure @jjeroch : in the ticket #574 the validator field is specified as 'The validator is given by the company ID'. Please clarify whether the column in database and the corresponding field in the endpoint's payload should be GUID or string (the PR currently implements string but this seems to be in conflict with the ticket).

**Comment by AnuragNagpure** [comment]
> @AnuragNagpure @jjeroch : in the ticket #574 the validator field is specified as 'The validator is given by the company ID'. Please clarify whether the column in database and the corresponding field in the endpoint's payload should be GUID or string (the PR currently implements string but this seems to be in conflict with the ticket).
> 
> Other than that the PR is fine. I did adjust the entities names (Companies -> Company) as the specified names were in conflict with existing naming conventions. (I also left a comment in the ticket about this). You need to pull my changes before applying further commits

Hi @ntruchsess  as per my discussion with julia she told me to keep it string currently we will get this field as null. In future there will be use of validator, currently we only have to add it in Get Endpoint response.

**Review by ntruchsess — APPROVED** [review]

**Pull request merged**
