### PR TITLE
chore(mailing template): improve email templates

### PR DESCRIPTION
**Pull request by manojava-gk**
## Description

removed redundant code. mention modules like header, content and footer

## Why

improve templates

## Issue

NA

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally

### CODE REVIEW

**Comment by jjeroch** [comment]
not yet ready for review - @Phil91 please take over the review as soon as mano finished the implementation and fixed the sonar findings. Evelyn might also look into it - please align between the both of you

**Comment by manojava-gk** [comment]
@evegufy Need your help in testing ```additional_user_invitation_with_message.html``` template where I have fixed code smell issues as well as redundant ```<style>``` tag has been removed

**Comment by evegufy** [comment]
@manojava-gk btw could you please remove this file: https://github.com/catenax-ng/tx-portal-backend/blob/updates/CPLP-2679-improve-email-template/src/mailing/Mailing.Template/EmailTemplates/README.md?
It's really old and due to that confusing by now.

**Comment by jjeroch** [comment]
A couple of findings - I did not run through all emails

**"Registration Declined"**
- content devider could not get loaded
- header "Quick Help" should be left aligned.
- afterwards to be checked if the central content message can stay in place or if the styling looks awkward. But need to see the complete email with the content devider before making a decision

**"Service Subcription Activated"**
- one more line break/space needed before footer starts
- top and bottom grey frame missing - refer to "Registration Declined"

**"Welcome to Catena-X - Registration Request Approved"**
- quick help url coloring is different - should be aligned - one color/styling for all urls
- top and bottom grey frame missing - refer to "Registration Declined"

**"Welcome to Catena-X - Your User Account got created"**
- quick help url coloring is different - should be aligned - one color/styling for all urls
- top and bottom grey frame missing - refer to "Registration Declined"

**"Your Catena-X Registration Password"**
- password should be central placed to fit to the rest of the email template

**"Congratulations - Your registration got successfully submitted"**
- footer has white space on the right and left side
- top and bottom grey frame missing - refer to "Registration Declined"
- message/text typo looks different to other emails
- i would place the content left aligned instead of central

**"Your Service request was declined"**
- top and bottom grey frame missing - refer to "Registration Declined"
- one more line break/space needed before footer starts

**"Service Subscription Request - Your Action is needed"**
- quick help url coloring is different - should be aligned - one color/styling for all urls
- footer has a different spacing compared to other templates
- email subject has a spelling error "Subscription"

**"Business Application Activated"**
- quick help url coloring is different - should be aligned - one color/styling for all urls
- footer has a different spacing compared to other templates

**Review by evegufy — APPROVED** [review]

**Pull request merged**
