### PR TITLE
fix(registration): unsupported bpdm identifier DUNS_ID

### PR DESCRIPTION
**Pull request by typecastcloud**
## Description

- Add missing DUNS_ID in BpdmIdentifiersId
- Add test theory for all BPDM types

**! Migration is missing !** please advise or add @ntruchsess @Phil91.

Maybe it is possible to filter types from bpdm gate endpoint for only supported types. This issue will happen whenever there is a new type added to BPDM project.

## Why

Whenever we receive a json with missing type, the onboarding bpdm creation step fails.

## Issue

[#618](https://github.com/eclipse-tractusx/portal-backend/issues/618)

## Checklist

Please delete options that are not relevant.

- [*] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [*] I have created and linked IP issues or requested their creation by a committer
- [*] I have performed a self-review of my own code
- [*] I have successfully tested my changes locally
- [*] I have added tests that prove my changes work
- [*] I have checked that new and existing tests pass locally with my changes

### CODE REVIEW

**Comment by jjeroch** [comment]
@typecastcloud  & @ntruchsess  this will impact likely the FE - I suggest to proceed with the PR but I need at least 1 week to test it fully on dev and to do the necessary FE changes.

**Comment by ntruchsess** [comment]
@typecastcloud : thank you for your contribution. As I do not have write-access to your repository I did pick your commits, created the missing migration and put all in new PR https://github.com/eclipse-tractusx/portal-backend/pull/624
I also added more asserts to the unit-test to validate the IdentifierTypeId is actually deserialized as expected.
I'll close this PR as obsolete as soon #624 is merged.

**Comment by typecastcloud** [comment]
> @typecastcloud : thank you for your contribution. As I do not have write-access to your repository I did pick your commits, created the missing migration and put all in new PR #624 I also added more asserts to the unit-test to validate the IdentifierTypeId is actually deserialized as expected. I'll close this PR as obsolete as soon #624 is merged.

I have this setting active:
image

Did it not work?

**Comment by typecastcloud** [comment]
Hi @ntruchsess, can you tell me if the option for "Allow edits by maintainers" does not work?

**Comment by ntruchsess** [comment]
> Hi @ntruchsess, can you tell me if the option for "Allow edits by maintainers" does not work?

I can verify it works. I just didn't try before ;-)

**Review by ntruchsess — APPROVED** [review]
technically this PR is ready to merge. What is missing is seeding-data for table country_assigned_identifiers. This data does not affect the service-call to bpdm, it affects submission of company-data referring to the new identifierType.
@jjeroch will decide whether this should be added there or will be tracked and added in a new issue + new PR.

**Comment by typecastcloud** [comment]
> @typecastcloud technically this PR is ready to merge. What is missing is seeding-data for table country_assigned_identifiers. This data does not affect the service-call to bpdm, it affects submission of company-data referring to the new identifierType.
> @jjeroch we need to decide whether this should be added here or should be tracked and added in a new issue + new PR.

Thank you @ntruchsess for the continuous effort.

**Review by ntruchsess — APPROVED** [review]
@jjeroch : from my point of view technically this PR is ready to merge, but we might consider an alternative solution. Please see my comment in #618

**Comment by ntruchsess** [comment]
PR #657 implements an alternative solution that ignores unknown bpdm-identifier-types during json-deserialization.

**Pull request closed without merging**
