### PR TITLE
feat(dim): add separate process steps for dim wallet

### PR DESCRIPTION
**Pull request by Phil91**
## Description

* implement the wallet creation for the dim wallet
* add retrigger endpoint to restarted a failed dim wallet step 
* add postback endpoint to receive the did document and  authentication information

## Why

To support the sap wallet

## Issue

Refs: #416 #478 #517

Link to corresponding PR in CD-repo: https://github.com/eclipse-tractusx/portal/pull/214

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by Phil91** [comment]
IP Check Issue can be found [here](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/13370)

**Review by ntruchsess — APPROVED** [review]
I did rebase on dev and clean up all issues. As we are not using functional primary-keys I did add Id to WalletData. For the same reason I also added Ids to OfferSubscriptionProcessData and OnboardingServiceProviderDetails, adjusting all related code and tests.
As the last two migrations were merged without propper rebase on each other I did add the missing code to the Designer of the createcertificate migration which (while being merged more early) would be applied later when updating the database all at once. This caused issues when doing a create-remove-recreate of the subsequent migration. Fortunally the createcertificates-migration only contains renaming of enum-labels, so it's unlikely this will ever cause more harm.
We should discuss whether WalletData.ClientSecret should be encrypted. Other than that please double-check.

**Comment by ntruchsess** [comment]
just discussed with @jjeroch that clientSecret shall be encrypted the same way as with onboardingserviceproviderdetails

**Review by ntruchsess — CHANGES_REQUESTED** [review]
just discussed with @jjeroch : the clientSecret in WalletData shall be encrypted the same way as done in OnboardingServiceProviderDetails

**Review by ntruchsess — APPROVED** [review]

**Pull request merged**
