### PR TITLE
fix(connector): fixed the edc discovery endpoint

### PR DESCRIPTION
**Pull request by dhiren-singh-007**
## Description

Fixed the EDC discovery endpoint by filtering an grouping it by Host 

## Why

Earlier its was filtering by provider which was showing managed connector under provider BPN which is incorrect.

## Issue

#1089 

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have checked that new and existing tests pass locally with my changes

### CODE REVIEW

**Comment by dhiren-singh-007** [comment]
@Phil91 : Can i update the Dependency as a blank file because in artifacts it is blank 
https://github.com/eclipse-tractusx/portal-backend/actions/runs/11551164069?pr=1120
Please help

**Comment by Phil91** [comment]
> @Phil91 : Can i update the Dependency as a blank file because in artifacts it is blank https://github.com/eclipse-tractusx/portal-backend/actions/runs/11551164069?pr=1120 Please help

@dhiren-singh-007 sometimes the workflow fails because the dependencies aren't build correctly. I'll restart the workflow again

**Review by Phil91 — CHANGES_REQUESTED** [review]
Since this change didn't affect the unit tests at all, could you please add a test case that would actually fail when using Provider instead of Host.

**Review by Phil91 — APPROVED** [review]

**Comment by dhiren-singh-007** [comment]
@Phil91 I thought that two reviewers which i selected will be treated as optional if one approves , so removed the other one.

**Pull request merged**
