### PR TITLE
fix(osp): added short name in company creation

### PR DESCRIPTION
**Pull request by dhiren-singh-007**
## Description

Added short name in company creation

## Why

Api had this field in request but was missing in the code while creating the company

## Issue

NA

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have checked that new and existing tests pass locally with my changes

### CODE REVIEW

**Comment by dhiren-singh-007** [comment]
@Phil91 can you please re-trigger the dependency workflow

**Review by Phil91 — APPROVED** [review]

**Review by Phil91 — COMMENTED** [review]
@dhiren-singh-007 could you please add one unit test or edit the existing one

**Comment by dhiren-singh-007** [comment]
> @dhiren-singh-007 could you please add one unit test or edit the existing one

Thanks @Phil91 for highlighting this , sure i will add .Also next time i will be more proactive to add/update the unit test.

**Review by Phil91 — DISMISSED** [review]

**Comment by Phil91** [comment]
@dhiren-singh-007 could you please create an issue and assign it under issue in the pr description

**Review by ntruchsess — APPROVED** [review]

**Pull request merged**
